to check
rendivy/CalculatorMAD pull request #1
Opened 2023-02-20 20:29 UTC by YuraYangel

2023-02-26 07:45 UTC, Chantreck requested changes
За compose лайк!

2023-02-26 07:45 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/MainActivity.kt
> +
Что-то как-то многовато пустых строк)

2023-02-26 07:45 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorButtonComponent.kt
> +var LabelColor = Color(230, 225, 229)
Вот это можно вынести в файл Color.kt, он для этого и предназначен

2023-02-26 07:45 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorButtonComponent.kt
> +}
Смотри, тебе нужно сделать всего один компонент для кнопки, ведь по факту все кнопки одинаковые, отличаются только текстом и действием, которое происходит при нажатии. Поэтому тебе достаточно просто передать текст и лямбду с нужным действием. А вот передавать expression не нужно, кнопка она глупая, она не должна знать, что есть какое-то выражение, которое меняется от нажатия на неё. Ну и можно сделать отдельный компонент для акцентных кнопок, а можешь просто передавать цвет в тот же компонент

2023-02-26 07:45 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorView.kt
> +                .padding(),
Modifier обычно указывается последним. А зачем здесь Box?

2023-02-26 07:45 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorView.kt
> +                }
После того, как ты сделаешь один компонент для кнопок (или еще один для акцентной), ты сможешь создавать кнопки очень легко и просто - буквально в цикле. Просто создаешь, например, дата-класс для информации о кнопки или еще лучше enum, потом матрицу из них (типа как они в макете), и проходишься по нему, создавая Row и свои кнопки

2023-02-26 07:45 UTC, Chantreck commented on app/src/main/res/values/colors.xml
> +    <color name = "displayColor">#1d1e27</color>
Если используешь эти цвета, то задавай их в Color.kt и не создавай даже этот файл

2023-02-26 07:45 UTC, Chantreck commented on app/src/main/res/values/dimen.xml
> +    <dimen name="ButtonShape">28.dp</dimen>
Вот эти размеры тоже лучше в обычном kotlin-файле задать

2023-02-26 07:45 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorButtonComponent.kt
> +        }
Вот эту обработку лучше вынести в файл с бизнес-логикой, кнопка должна просто вызывать функцию и не думать ни о чем

2023-02-26 07:46 UTC, Chantreck commented
Изменения можешь делать в этой же ветке, они автоматически добавятся в реквест

2023-03-10 11:05 UTC, Chantreck requested changes

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/ui/theme/Type.kt
> +
Емаё, Юра, нажимай Ctrl+Alt+L после того, как заканчиваешь код писать, много магии произойдет)

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/ui/theme/TextSize.kt
> +var LabelSize = 24.sp
Зачем `var`, это же константа, сделай `val`

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorButtonComponent.kt
> +fun ButtonModel(symbol: String, onClick: (String) -> Unit, color: Color, fontSize: TextUnit){
На вход лучше принимать не строковый `symbol`, а непосредственно `ActionEnum`, чтобы сделать безопаснее функцию, которая будет обрабатывать нажатие, поскольку мы ограничиваем допустимые входные значения

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorButtonComponent.kt
> +fun DeleteButton(expression: MutableState<String>){
Кнопка должна просто принимать на вход лямбду, которая будет выполняться при нажатии на неё, она не должна знать, что за expression и что ей с ним делать. Поэтому здесь подойдёт просто `onClick: () -> Unit`

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorView.kt
> +        )
А зачем тебе здесь Column? Ты же и так внутри Column всё располагаешь

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorView.kt
> +                top = MainExpressionPadding)
Такие паддинги лучше задать у всей Column, поскольку как минимум отступы по бокам у всех элементов одинаковые, меньше нужно будет задавать

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorView.kt
> +                )
Вот этот `Row` лучше вынести в отдельный компонент, иначе раздуваешь основной компонент сильно. К тому же тут раз мы создаём эти ряды в цикле, вынести компонент само по себе напрашивается. А внутри компонента задавай кнопки в цикле (с маленькой проверкой внутри на `ZERO`, но только не сравнивай `symbol`, сравнивай `ActionEnum`, иначе никакого толку от того, что мы его добавили)

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorButtonComponent.kt
> +fun getButtonColor(buttonSymbol: ActionEnum): Color{
Что-то я не заметил, где используются эта функция и следующая, они точно нужны? И тем более точно ли они должны быть Composable?

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +    }
Давай лучше просто сделаем так `expression.value.drop(1)`. Если хочешь всё же использовать цикл, то используй `StringBuilder`, он специально оптимизирован для сбора строк в цикле

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +
Фактически неявно ты здесь сделал ViewModel, советую все же всё это обернуть в класс и использовать его вместо просто набора функций. На производительности это никак не скажется, компилятор это всё равно всё в класс соберёт

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +fun handleButtonClick(buttonSymbol: ActionEnum, expression: MutableState<String>) {
Если сделаешь класс, то expression лучше хранить в нём

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +             if (buttonSymbol.symbol.isNumber()){
Так как у тебя ActionEnum имеет ограниченное количество знаний, а все не-цифры ты уже обработал, это условие лишнее

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +fun addNumberOnExpression(buttonSymbol: ActionEnum, expression: MutableState<String>){
Все подобные функции лучше сделать приватными, даже если не будешь создавать класс

2023-03-10 11:05 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +fun calculate(expression: MutableState<String>){
Что-то у тебя тут слишком длинная функция, по-хорошему так быть не должно. Либо можно хранить операнды отдельно, а не парсить, либо использовать регулярные выражения в конце концов, зря что ли учите)

2023-03-10 11:21 UTC, rendivy commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorButtonComponent.kt
> +fun getButtonColor(buttonSymbol: ActionEnum): Color{
@Chantreck Первая меняет по символу из кнопки цвет самой кнопки, а вторая изменяет цвет кнопки удаления, когда поле для чисел полностью пустое
```suggestion
ButtonModel(
    buttonSymbol = buttonSymbol,
    onClick = { handleButtonClick(buttonSymbol, expression) },
    color = getButtonColor(buttonSymbol),
    fontSize = fontSize
    )
```

2023-03-11 06:30 UTC, merged