Проверка динамических тем
rendivy/CalculatorMAD pull request #3
Opened 2023-03-11 05:10 UTC by rendivy

2023-03-15 05:50 UTC, Chantreck requested changes
Работать и работать еще! Только в следующий раз не сливай реквесты без аппрува, а то я буду сильно ругаться

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorButtonComponent.kt
> +    buttonSymbol: ActionEnum, onClick: (String) -> Unit, color: Color, fontSize: TextUnit,
Зачем в onClick передавать строку, если можно сам ActionEnum?

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorView.kt
> +    DynamicTheme(darkTheme = true) {
`DynamicTheme` наверное стоит перенести в `CalculatorView`, она же должна применяться ко всем элементам

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/ActionEnum.kt
> +enum class ActionEnum(var symbol: String) {
Зачем `var`? Ты же не можешь изменить символ

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +val expression: MutableState<String> = mutableStateOf("")
Это нужно сделать членами класса `CalculatorAction`, иначе, если ты оставляешь их на верхнем уровне, то компилятор создаст класс `CalculatorActionKt`, членами которого станут эти переменные, и ты создаешь неявную зависимость от этого класса

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +            }
Обычно в котлине если действие в кейсе одно, его записывают без фигурных скобок. В твоем случае особенно актуально, потому что кейсов много

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/ui/theme/Type.kt
> +)
Вот это что? Не надо создавать пустые классы/переменные

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +    }
Вот этих функций здесь точно не должно быть. Этот класс - класс бизнес-логики, никаких composable-штук в нем быть не должно. Считай, что этот класс можно было бы скопировать и вставить в консольное приложение и он должен работать точно так же. Перенести эти функции в CalculatorView, где они собственно и используются

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +    fun changeDelColor(): Color {
Этой функции тоже здесь не место

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +            expression.value += "/"
А здесь почему тогда не сделал через `ActionEnum`?)

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +    private fun isOperatorInExpression(): Boolean {
Выглядит очень неэффективно. На мой взгляд, лучше вынести в флаг, который будет становиться `true` при добавлении операции и `false` при вычислении результата или стиранию символа

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +        var newExpression = ""
Выноси строки в константы

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +            result = (result.toDouble() * 0.01).toString()
Такие числа тоже

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +            if (exp[i] == '+') {
Вот такой огромный `if`/`else` лучше заменить на `when`, он для этого и создан

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +            firstNumber += exp[0]
Если ты не хочешь сохранять операнды, то хотя бы их поиск вынеси в отдельные функции, чтобы не загромождать эту

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +        if (!isOperatorInExpression()) {
Можно применить инверсию условия, чтобы уменьшить вложенность. Тогда получится:
```kotlin
if (isOperatorInExpression()) return

//остальной код
```

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +        if (!doubleInExpression) {
Здесь тоже очень уместна инверсия условия

2023-03-15 05:50 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +        if (!actionIsClicked and !errorInString) {
И вообще во всех функциях, где у тебя код выполняется только при каком-то условии. Но вообще это не очень хорошо писать такой код, но это уже на 3 курсе узнаешь

2023-03-15 06:46 UTC, rendivy commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +            expression.value += "/"
@Chantreck у меня же в Enum находятся нестандартные знаки деления и умножения, поэтому если я просто добавлю Enum в свою строку, то у меня не получится её посчитать

2023-03-15 06:49 UTC, rendivy commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +        var newExpression = ""
@Chantreck а как её вынести в константу? Я же дальше собираю в неё новую строку и её приходится так инициализировать

2023-03-15 08:10 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +            expression.value += "/"
Почему? Ты можешь просто их отображать на экране и потом искать эти же символы

2023-03-15 12:56 UTC, Chantreck requested changes

2023-03-15 12:56 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/CalculatorView.kt
> +fun TextView() {
Все функции отсюда и до конца можно сделать `private`, чтобы они были доступны только из этого файла

2023-03-15 12:56 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +
В `when` пустые строки не нужны)

2023-03-15 12:56 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +        if (actionIsClicked) {
Здесь бы тоже инверсию условия сделать неплохо было бы

2023-03-15 12:56 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +        var newExpression = ""
```kotlin
const val EMPTY_STRING = ""
...
var newExpression = EMPTY_STRING
```

2023-03-15 12:56 UTC, Chantreck commented on app/src/main/java/com/example/secondtask_composecalculator/data/CalculatorAction.kt
> +            '+' -> result = (firstNumber.toDouble() + secondNumber.toDouble()).toString()
Можно написать функцию-расширение для `enum`, чтобы по символу находить нужное значение `enum`, а здесь уже сравнивать сами значения

2023-03-16 03:32 UTC, Chantreck approved these changes

2023-03-16 07:50 UTC, merged